function controltest(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',hb='&',r='/',Ab='7A1197A752C88D77F624C4F194856522.cache.html',cc='<script defer="defer">controltest.onInjectionDone(\'controltest\')<\/script>',gc='<script id="',A='=',q='?',C='Bad handler "',bc='DOMContentLoaded',o='SCRIPT',lb='Unexpected exception in locale detection, using default: ',kb='_',ib='__gwt_Locale',fc='__gwt_marker_controltest',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',m='controltest',jb='default',ec='end',tb='gecko',ub='gecko1_8',yb='gwt.hybrid',Bb='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',ac='head',xb='hosted.html?controltest',Fb='href',sb='ie6',ab='iframe',t='img',bb="javascript:''",Cb='link',wb='loadExternalRefs',fb='locale',gb='locale=',v='meta',eb='moduleRequested',dc='moduleStartup',rb='msie',w='name',ob='opera',db='position:absolute;width:0;height:0;border:none',Db='rel',qb='safari',zb='selectingPermutation',x='startup',Eb='stylesheet',vb='unknown',mb='user.agent',pb='webkit';var ic=window,k=document,hc=ic.__gwtStatsEvent?function(a){return ic.__gwtStatsEvent(a)}:null,Cc,sc,nc,mc=l,vc={},Fc=[],Bc=[],lc=[],yc,Ac;hc&&hc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!ic.__gwt_stylesLoaded){ic.__gwt_stylesLoaded={}}if(!ic.__gwt_scriptsLoaded){ic.__gwt_scriptsLoaded={}}function rc(){var b=false;try{b=ic.external&&(ic.external.gwtOnLoad&&ic.location.search.indexOf(yb)==-1)}catch(a){}rc=function(){return b};return b}
function uc(){if(Cc&&sc){var c=k.getElementById(m);var b=c.contentWindow;if(rc()){b.__gwt_getProperty=function(a){return oc(a)}}controltest=null;b.gwtOnLoad(yc,m,mc);hc&&hc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:ec})}}
function pc(){var j,h=fc,i;k.write(gc+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){mc=f(j.src)}if(mc==l){var e=k.getElementsByTagName(s);if(e.length>0){mc=e[e.length-1].href}else{mc=f(k.location.href)}}else if(mc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=mc+u;mc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function zc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}vc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{Ac=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{yc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function kc(a,b){return b in Fc[a]}
function jc(a){var b=vc[a];return b==null?null:b}
function oc(d){var e=Bc[d](),b=Fc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(Ac){Ac(d,a,e)}throw null}
var qc;function tc(){if(!qc){qc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);hc&&hc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(mc+Dc)}}
Bc[fb]=function(){try{var g;if(g==null){var b=location.search;var h=b.indexOf(gb);if(h>=0){var e=b.substring(h);var c=e.indexOf(A)+1;var d=e.indexOf(hb);if(d==-1){d=e.length}g=e.substring(c,d)}}if(g==null){g=jc(fb)}if(g==null){g=ic[ib]}if(g==null){return jb}while(!kc(fb,g)){var f=g.lastIndexOf(kb);if(f==-1){g=jb;break}else{g=g.substring(0,f)}}return g}catch(a){alert(lb+a);return jb}};Fc[fb]={'default':0,zh:1};Bc[mb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(ob)!=-1){return ob}else if(d.indexOf(pb)!=-1){return qb}else if(d.indexOf(rb)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return sb}}}else if(d.indexOf(tb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return ub}return tb}return vb};Fc[mb]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};controltest.onScriptLoad=function(){if(qc){sc=true;uc()}};controltest.onInjectionDone=function(){Cc=true;hc&&hc({moduleName:m,subSystem:x,evtGroup:wb,millis:(new Date()).getTime(),type:ec});uc()};pc();var Dc;if(rc()){if(ic.external.initModule&&ic.external.initModule(m)){ic.location.reload();return}Dc=xb}zc();hc&&hc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:zb});if(!Dc){try{Dc=Ab}catch(a){return}}var xc;function wc(){if(!nc){nc=true;if(!__gwt_stylesLoaded[Bb]){var a=k.createElement(Cb);__gwt_stylesLoaded[Bb]=a;a.setAttribute(Db,Eb);a.setAttribute(Fb,mc+Bb);k.getElementsByTagName(ac)[0].appendChild(a)}uc();if(k.removeEventListener){k.removeEventListener(bc,wc,false)}if(xc){clearInterval(xc)}}}
if(k.addEventListener){k.addEventListener(bc,function(){tc();wc()},false)}var xc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){tc();wc()}},50);hc&&hc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:ec});hc&&hc({moduleName:m,subSystem:x,evtGroup:wb,millis:(new Date()).getTime(),type:nb});k.write(cc)}
controltest();