function gwtflow(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',hb='&',qc='../gxt/css/gxt-all.css',r='/',fc='08844727AF9975AB821E0B70417C21F4.cache.html',cc='27B53EEB43F592F8181381BB122D987E.cache.html',gc='66745257CA859190C707DE3D94B032F8.cache.html',Fb='6C7C7DC8E532E87BBEE60A1B16FEAF07.cache.html',Db='8A740974D7C483CCC87BC575FD1D8FF2.cache.html',ic='926FEA8E055A23C83A87AFD721971F3A.cache.html',ec='98ED72ACA2DB1BDB4664EFC75851DFB6.cache.html',sc='<script defer="defer">gwtflow.onInjectionDone(\'gwtflow\')<\/script>',uc='<script id="',A='=',q='?',Eb='AC1148CE839205F9156F6826146BBA34.cache.html',ac='B4137438EFD2907BAABCB1700046AF56.cache.html',bc='BC7058ED820466833D40C62E373EBFE9.cache.html',C='Bad handler "',Bb='C2398E1ECE7478C56D78A4335330DB88.cache.html',rc='DOMContentLoaded',hc='F5AFC6B7C891B3DEB1EE61D3ADFDC4E3.cache.html',o='SCRIPT',lb='Unexpected exception in locale detection, using default: ',kb='_',ib='__gwt_Locale',tc='__gwt_marker_gwtflow',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',jb='default',oc='end',ub='gecko',vb='gecko1_8',yb='gwt.hybrid',jc='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',m='gwtflow',pc='head',zb='hosted.html?gwtflow',nc='href',tb='ie6',sb='ie8',ab='iframe',t='img',bb="javascript:''",kc='link',xb='loadExternalRefs',fb='locale',gb='locale=',v='meta',eb='moduleRequested',dc='moduleStartup',rb='msie',w='name',ob='opera',db='position:absolute;width:0;height:0;border:none',lc='rel',qb='safari',Ab='selectingPermutation',x='startup',mc='stylesheet',wb='unknown',mb='user.agent',pb='webkit',Cb='zh';var wc=window,k=document,vc=wc.__gwtStatsEvent?function(a){return wc.__gwtStatsEvent(a)}:null,kd,ad,Bc,Ac=l,dd={},nd=[],jd=[],zc=[],gd,id;vc&&vc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!wc.__gwt_stylesLoaded){wc.__gwt_stylesLoaded={}}if(!wc.__gwt_scriptsLoaded){wc.__gwt_scriptsLoaded={}}function Fc(){var b=false;try{b=wc.external&&(wc.external.gwtOnLoad&&wc.location.search.indexOf(yb)==-1)}catch(a){}Fc=function(){return b};return b}
function cd(){if(kd&&ad){var c=k.getElementById(m);var b=c.contentWindow;if(Fc()){b.__gwt_getProperty=function(a){return Cc(a)}}gwtflow=null;b.gwtOnLoad(gd,m,Ac);vc&&vc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:oc})}}
function Dc(){var j,h=tc,i;k.write(uc+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){Ac=f(j.src)}if(Ac==l){var e=k.getElementsByTagName(s);if(e.length>0){Ac=e[e.length-1].href}else{Ac=f(k.location.href)}}else if(Ac.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=Ac+u;Ac=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function hd(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}dd[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{id=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{gd=eval(b)}catch(a){alert(C+b+F)}}}}}}
function yc(a,b){return b in nd[a]}
function xc(a){var b=dd[a];return b==null?null:b}
function md(d,e){var a=zc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function Cc(d){var e=jd[d](),b=nd[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(id){id(d,a,e)}throw null}
var Ec;function bd(){if(!Ec){Ec=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);vc&&vc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(Ac+ld)}}
jd[fb]=function(){try{var g;if(g==null){var b=location.search;var h=b.indexOf(gb);if(h>=0){var e=b.substring(h);var c=e.indexOf(A)+1;var d=e.indexOf(hb);if(d==-1){d=e.length}g=e.substring(c,d)}}if(g==null){g=xc(fb)}if(g==null){g=wc[ib]}if(g==null){return jb}while(!yc(fb,g)){var f=g.lastIndexOf(kb);if(f==-1){g=jb;break}else{g=g.substring(0,f)}}return g}catch(a){alert(lb+a);return jb}};nd[fb]={'default':0,zh:1};jd[mb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(ob)!=-1){return ob}else if(d.indexOf(pb)!=-1){return qb}else if(d.indexOf(rb)!=-1){if(document.documentMode>=8){return sb}else{var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){var e=b(c);if(e>=6000){return tb}}}}else if(d.indexOf(ub)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return vb}return ub}return wb};nd[mb]={gecko:0,gecko1_8:1,ie6:2,ie8:3,opera:4,safari:5};gwtflow.onScriptLoad=function(){if(Ec){ad=true;cd()}};gwtflow.onInjectionDone=function(){kd=true;vc&&vc({moduleName:m,subSystem:x,evtGroup:xb,millis:(new Date()).getTime(),type:oc});cd()};Dc();var ld;if(Fc()){if(wc.external.initModule&&wc.external.initModule(m)){wc.location.reload();return}ld=zb}hd();vc&&vc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:Ab});if(!ld){try{md([jb,sb],Bb);md([Cb,ob],Db);md([Cb,qb],Eb);md([Cb,vb],Fb);md([Cb,ub],ac);md([Cb,tb],bc);md([jb,ob],cc);md([jb,qb],ec);md([jb,vb],fc);md([jb,ub],gc);md([Cb,sb],hc);md([jb,tb],ic);ld=zc[Cc(fb)][Cc(mb)]}catch(a){return}}var fd;function ed(){if(!Bc){Bc=true;if(!__gwt_stylesLoaded[jc]){var a=k.createElement(kc);__gwt_stylesLoaded[jc]=a;a.setAttribute(lc,mc);a.setAttribute(nc,Ac+jc);k.getElementsByTagName(pc)[0].appendChild(a)}if(!__gwt_stylesLoaded[qc]){var a=k.createElement(kc);__gwt_stylesLoaded[qc]=a;a.setAttribute(lc,mc);a.setAttribute(nc,Ac+qc);k.getElementsByTagName(pc)[0].appendChild(a)}cd();if(k.removeEventListener){k.removeEventListener(rc,ed,false)}if(fd){clearInterval(fd)}}}
if(k.addEventListener){k.addEventListener(rc,function(){bd();ed()},false)}var fd=setInterval(function(){if(/loaded|complete/.test(k.readyState)){bd();ed()}},50);vc&&vc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:oc});vc&&vc({moduleName:m,subSystem:x,evtGroup:xb,millis:(new Date()).getTime(),type:nb});k.write(sc)}
gwtflow();